version: "3.8"
services:
    web:
        build:
            context: ./
            target: production
        volumes:
            - .:/src
        command: npm run start
        restart: always
        environment:
            NODE_ENV: production
            DEBUG: nodejs-docker-express:*
        labels:
            com.centurylinklabs.watchtower.enable: false
