services:
    web:
        container_name: Awotifier
        build:
            context: ./
            target: production
        volumes:
            - .:/src
        command: npm run start
        restart: always
        environment:
            NODE_ENV: production
            DEBUG: nodejs-docker-express:*
            TOKEN: ${TOKEN}
        labels:
            com.centurylinklabs.watchtower.enable: false
